# Tide Island: user permissions for battery charge threshold & conservation mode
z /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode 0666 root root -
z /sys/class/power_supply/BAT*/charge_control_end_threshold 0666 root root -
